# setting > cicd > Variables: REGISTRY_URL, REGISTRY_PROJECT, 
# keyword: gitlab runner Variables
# registry.nnson128.io.vn/elroy/shoeshop:staging_0.0.11_4b1d2b6b
variables:
  DOCKER_IMAGE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  DOCKER_CONTAINER: ${CI_PROJECT_NAME}

stages:
  - buildandpush
  - deploy
  - showlog

buildandpush:
  stage: buildandpush
  variables:
    GIT_STRATEGY: clone
  before_script: 
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker build -t ${DOCKER_IMAGE} . 
    - docker push ${DOCKER_IMAGE}
  tags:
    - lab-server
  only:
    - tags

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script: 
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker pull ${DOCKER_IMAGE}
    - docker rm -f ${DOCKER_CONTAINER} || echo "No existing container to remove"
    - docker run --name ${DOCKER_CONTAINER} -dp 9999:9999 ${DOCKER_IMAGE}
  tags:
    - lab-server
  only:
    - tags

showlog:
  stage: showlog
  variables:
    GIT_STRATEGY: none
  script:
    - sleep 20
    - docker logs ${DOCKER_CONTAINER}
  tags:
    - lab-server
  only:
    - tags
  when: manual
