variables:
  PROJECT_NAME: shoe-ShoppingCart
  PROJECT_VERSION: 0.0.1-SNAPSHOT
  PROJECT_USER: shoeshop
  PROJECT_PATH: /datas/$PROJECT_USER
  LOG_FILE: /datas/$PROJECT_USER/nohup.out

stages:
  - build
  - deploy
  - showlog

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - mvn install -DskipTests=true || { echo "Build failed"; exit 1; }
  tags:
    - lab-server
  only:
    - tags

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - |
      # Authorization check
      if [ "$GITLAB_USER_LOGIN" != "nnson128" ]; then
        echo "Permission denied: Only user 'nnson128' is authorized to deploy."
        exit 1
      fi

      # Deployment steps
      sudo cp ./target/$PROJECT_NAME-$PROJECT_VERSION.jar $PROJECT_PATH/
      sudo chown -R $PROJECT_USER:$PROJECT_USER $PROJECT_PATH
      sudo su $PROJECT_USER -c "
        PID=\$(ps -ef | grep '$PROJECT_NAME-$PROJECT_VERSION.jar' | grep -v grep | awk '{print \$2}');
        if [ -n \"\$PID\" ]; then
          echo \"Stopping existing process with PID \$PID\";
          kill \$PID;
          sleep 2;
          [ -n \"\$(ps -p \$PID -o pid=)\" ] && kill -9 \$PID;
        fi;
        echo \"Starting new process...\";
        cd $PROJECT_PATH;
        nohup java -jar $PROJECT_NAME-$PROJECT_VERSION.jar > $LOG_FILE 2>&1 &
      "
  tags:
    - lab-server
  only:
    - tags
showlog:
  stage: showlog
  variables:
    GIT_STRATEGY: none
  script:
    - sudo su $PROJECT_USER -c "tail -n 10000 $LOG_FILE"
  tags:
    - lab-server
  only:
    - tags
  when: manual
