### 1
stages:
  - build
  - deploy
  - checklog
build:
  stage: build
  script:
    - whoami
    - pwd
    - ls -l
  tags:
    - lab-server


### 2
stages:
  - build
  - deploy
  - checklog
build:
  stage: build
  script:
    - mvn install -DskipTests=true
  tags:
    - lab-server

### 3: error cause:
### each stage will run in a new clone repo 
stages: 
  - build
  - deploy
  - checklog
build: 
    stage: build
    script: 
        - mvn install -DskipTests=true
    tags:
        - lab-server

deploy: 
    stage: deploy
    script: 
        - java -jar ./target/shoe-ShoppingCart-0.0.1-SNAPSHOT.jar
    tags: 
        - lab-server

### 4
stages: 
  - build
  - deploy
  - checklog
build: 
    stage: build
    variables:
        GIT_STRATEGY: clone
    script: 
        - mvn install -DskipTests=true
    tags:
        - lab-server

deploy: 
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script: 
        - java -jar ./target/shoe-ShoppingCart-0.0.1-SNAPSHOT.jar
    tags: 
        - lab-server
